const express = require('express');
const router = express.Router();

const statusUser = require('./adminRoutes/statusUser');
const deleteDenuncia = require('./adminRoutes/deleteDenuncia');
const detallesDenuncia = require('./adminRoutes/detallesDenuncia');
const estadoDenuncia = require('./adminRoutes/estadoDenuncia');
const getAllDenuncias = require('./adminRoutes/getAllDenuncias');
const getAllUsers = require('./adminRoutes/getAllUsers');
const getUser = require('./adminRoutes/getUser');
const addAdmin = require('./adminRoutes/addAdmin');
const loginAdmin = require('./adminRoutes/loginAdmin');
const veirifyAdmin = require('./adminRoutes/verifyAdmin');
const asignarPersonal = require('./adminRoutes/asignarPersonal');
const respuestaPredeterminada = require('./adminRoutes/respuestaPredeterminada');
const gestionPersonal = require('./adminRoutes/gestionPersonal');
const historialDenuncia = require('./adminRoutes/historialDenuncia');
const validarDenuncia = require('./adminRoutes/validarDenuncia');
const invalidarDenuncia = require('./adminRoutes/invalidarDenuncia');
const marcarNoAtendible = require('./adminRoutes/marcarNoAtendible');

router.use('/changeStatusUser', statusUser);
router.use('/deleteDenuncia', deleteDenuncia);
router.use('/detallesDenuncia', detallesDenuncia);
router.use('/estadoDenuncia', estadoDenuncia);
router.use('/getAllDenuncias', getAllDenuncias);
router.use('/getAllUsers', getAllUsers);
router.use('/getUser', getUser);
router.use('/addAdmin', addAdmin);
router.use('/loginAdmin', loginAdmin);
router.use('/verifyAdmin', veirifyAdmin);
router.use('/asignarPersonal', asignarPersonal);
router.use('/respuestaPredeterminada', respuestaPredeterminada);
router.use('/personal', gestionPersonal);
router.use('/historialDenuncia', historialDenuncia);
router.use('/denuncias', validarDenuncia);
router.use('/denuncias', invalidarDenuncia);
router.use('/denuncias', marcarNoAtendible);

module.exports = router;
